---
title: "Untitled"
output:
  html_document: default
  pdf_document: default
date: "2025-05-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(brms)
library(dplyr)
library(ggplot2)
library(tidybayes)
library(ggdist)
library(tidyr)
library(purrr)
library(cowplot)
library(ggsignif)
library(scales)
library(purrr)
library(modelr)
```

# Load data

```{r}
exp_df = read.csv("experiment_data/exp_df_real_exp.csv")
head(exp_df)
```

# Filter data based on the criteria in the pre-registration

```{r}
no_revise_prolific_pids = (exp_df %>% group_by(PROLIFIC_PID, AI, explanation) %>% summarise(a = sum(human_response == hai_response)) %>% filter(a == 12))$PROLIFIC_PID
consecutive_human_response = c(1)
for (i in 2:length(exp_df$human_response)) {
  if (exp_df$human_response[[i]] == exp_df$human_response[[i-1]]) {
    consecutive_human_response = c(consecutive_human_response, consecutive_human_response[i-1] + 1)
  } else {
    consecutive_human_response = c(consecutive_human_response, 1)
  }
}
exp_df$consecutive_human_response = consecutive_human_response

consecutive_hai_response = c(1)
for (i in 2:length(exp_df$hai_response)) {
  if (exp_df$hai_response[[i]] == exp_df$hai_response[[i-1]]) {
    consecutive_hai_response = c(consecutive_hai_response, consecutive_hai_response[i-1] + 1)
  } else {
    consecutive_hai_response = c(consecutive_hai_response, 1)
  }
}
exp_df$consecutive_hai_response = consecutive_hai_response
repeat_response_prolific_pids = (exp_df %>% group_by(PROLIFIC_PID, AI, explanation) %>% summarise(a = any((consecutive_hai_response >= 5) | (consecutive_human_response >= 5))) %>% filter(a == T))$PROLIFIC_PID

high_rel_error_prolific_pid = (exp_df %>% group_by(PROLIFIC_PID, AI, explanation) %>% summarise(a = ((human_response * 1000 - SalePrice) > 5 * SalePrice) & ((hai_response * 1000 - SalePrice) > 5 * SalePrice)) %>% filter(a == T))$PROLIFIC_PID


filtered_exp_df = exp_df |> 
  filter(!(PROLIFIC_PID %in% high_rel_error_prolific_pid) & !(PROLIFIC_PID %in% repeat_response_prolific_pids) & !(PROLIFIC_PID %in% no_revise_prolific_pids))
```

# Duration

```{r}
duration_df = read.csv("experiment_data/human-AI-house-pricing-real-exp1_November 16, 2025_18.36.csv")

filtered_response_id = unique(filtered_exp_df$ResponseId)
duration_df = duration_df %>% select(ResponseId, Duration..in.seconds., AI, explanation) %>% filter(ResponseId %in% filtered_response_id) %>% mutate(Duration..in.seconds. = as.numeric(Duration..in.seconds.)) %>% filter(!is.na(Duration..in.seconds.))
duration_df %>% group_by(AI, explanation) %>% summarise(duration = mean(Duration..in.seconds.)/60, duration25 = quantile(Duration..in.seconds., 0.25)/60, duration75 = quantile(Duration..in.seconds., 0.75)/60)
```

# Anchoring on AI

```{r}
filtered_exp_df %>% 
  mutate(ai_pred = ifelse(AI == "pred1", pred1, pred2)) %>%
  mutate(distance_to_ai = abs(hai_response * 1000 - ai_pred) / SalePrice,
         distance_to_h = abs(hai_response - human_response) / SalePrice * 1000) %>%
  group_by(AI, explanation) %>%
  summarise(mean_distance_to_ai = mean(distance_to_ai),
            distance_to_ai25 = quantile(distance_to_ai, 0.25),
            distance_to_ai75 = quantile(distance_to_ai, 0.75),
            mean_distance_to_h = mean(distance_to_h),
            distance_to_h25 = quantile(distance_to_h, 0.25),
            distance_to_h75 = quantile(distance_to_h, 0.75),
            n = n()/12)
```

# Plot the distribution of relevant error

```{r}

exp_df.mod = filtered_exp_df %>%
  pivot_longer(cols = c(human_response, hai_response), names_to = "block", values_to = "response", names_pattern = "([a-z]+)_response") |> 
  mutate(rel_error = (response*1000 - SalePrice)/SalePrice)
  # filter(abs(rel_error) <= 5)
exp_df.mod |> 
  ggplot() +
  geom_density(aes(x = rel_error), color = "red", size = 1, alpha = 1) +
  geom_vline(aes(xintercept = 0), size = 1, alpha = 1) +
  coord_cartesian(xlim = c(-2, 5)) +
  facet_grid(AI ~ explanation) +
  labs(subtitle = "Posterior predictive distribution for probability of superiority") +
  theme(panel.grid = element_blank())
```

# Fit the model
```{r}
priors_rel_error <-  c(
  # Priors for fixed effects of the location (rel_error)
  prior(normal(0, 1), class = b),
  prior(normal(0, 2.5), class = Intercept),

  # Priors for random effects of the location (rel_error)
  prior(cauchy(0, 1), class = sd, group = "PROLIFIC_PID"),

  # Priors for fixed effects of the scale (sigma)
  prior(normal(0, 1), class = b, dpar = "sigma"),
  prior(normal(0, 2.5), class = Intercept, dpar = "sigma"),

  # Priors for random effects of the scale (sigma)
  prior(cauchy(0, 1), class = sd, group = "PROLIFIC_PID", dpar = "sigma"),

  # Prior for the degrees of freedom (nu)
  prior(gamma(2, 0.1), class = nu)
)
```


```{r}
rel_error_model = brm(data = exp_df.mod, 
                   formula = bf(rel_error ~ AI*explanation + block + (1| PROLIFIC_PID), 
                                   sigma ~ AI*explanation + block + (1| PROLIFIC_PID)),
              prior = priors_rel_error, family = "student",
              iter = 20000, warmup = 8000, chains = 4, cores = 4,
              file = "brms_model_fits/lo_rel_error_mdl")
rel_error_model
```

# Plot the posterior predictive distribution for relevant error

```{r}
exp_df.mod %>% 
  data_grid(AI, explanation, block, PROLIFIC_PID) |> 
  add_predicted_draws(rel_error_model, ndraws = 100, re_formula = NA) %>%
  ggplot() +
  # geom_density(data = exp_df.mod, aes(x = rel_error), color = "red", size = 1, alpha = 1) +
  geom_density(aes(x = .prediction, group = .draw), color = "blue", size = 1, alpha = 0.1) +
  geom_vline(aes(xintercept = 0), size = 0.5, alpha = 1) +
  xlim(-5, 5) +
  scale_y_continuous(NULL, breaks = NULL) +
  facet_wrap(vars(AI, explanation)) +
  labs(subtitle = "Posterior predictive distribution for relevant error") +
  theme_minimal()
```

# Plot the reduction in APE

```{r}
plot_df = filtered_exp_df %>%
  mutate(row_id = row_number(),
         block = list(c("human", "hai"))) %>%
  unnest(block) %>%
  add_predicted_draws(rel_error_model, ndraws = 500, seed = 1234, re_formula = NULL) %>%
  pivot_wider(names_from = block, values_from = .prediction) %>%
  group_by(row_id, AI, explanation) %>% 
  summarise(human = mean(human, na.rm = T), hai = mean(hai, na.rm = T))
```

```{r}
bar_plot_df = rbind(plot_df %>%
  group_by(explanation, AI) %>%
  summarise(mean_payoff = mean(abs(human) - abs(hai)),
            sd_payoff = sd(abs(human) - abs(hai)),
            e = qt(0.975,df=n()-1)*sd_payoff/sqrt(n())),
  plot_df %>%
  group_by(AI) %>%
  summarise(mean_payoff = mean(abs(human) - abs(hai)),
            sd_payoff = sd(abs(human) - abs(hai)),
            e = qt(0.975,df=n()-1)*sd_payoff/sqrt(n())) %>%
    mutate(explanation = "Collapsing all explanations")) %>%
  mutate(explanation = ifelse(explanation == "both", "ILIV-SHAP and SHAP", ifelse(explanation == "shap", "SHAP", ifelse(explanation == "none", "None", explanation)))) %>%
  mutate(AI = ifelse(AI == "pred1", "AI1", "AI2")) %>%
  mutate(explanation = factor(explanation,
                        levels = c("ILIV-SHAP and SHAP", "SHAP", "None", "Collapsing all explanations"))) %>%
  arrange(explanation, AI)

sample_size_df = rbind(filtered_exp_df %>% mutate(explanation = factor(explanation, levels = c("both", "shap", "none"))) %>% group_by(explanation, AI) %>% summarise(n = n()),
                       filtered_exp_df %>% group_by(AI) %>% summarise(n = n()) %>% mutate(explanation = "collapse"))
```

```{r}
dev_d = 0.21
sample_annotation_df = data.frame(x = rep(1:4, each = 2) + rep(c(-dev_d, dev_d), 4),
                           y = 0.01,
                           label = paste("N = ", sample_size_df$n))

annotation_df = data.frame(x = rep(1:4, each = 2) + rep(c(-dev_d, dev_d), 4),
                           y = bar_plot_df$mean_payoff + bar_plot_df$e + 0.01,
                           label = paste(paste(round(bar_plot_df$mean_payoff, digits = 4) * 100, "%", sep=""),
                                         "\n [",
                                         paste(round(bar_plot_df$mean_payoff - bar_plot_df$e, digits = 4) * 100, "%", sep=""),
                                         ", ",
                                         paste(round(bar_plot_df$mean_payoff + bar_plot_df$e, digits = 4) * 100, "%", sep=""),
                                         "]", sep=""))
bar_plot_df %>%
  ggplot() +
  geom_bar(aes(y = mean_payoff, x = explanation, fill = AI), stat = "identity", color = NA,
             position=position_dodge(), alpha = .7) +
  geom_errorbar(
    aes(ymin = mean_payoff - e, ymax = mean_payoff + e, x = explanation, group =  AI),
    position = position_dodge(width = 0.9),
    width = 0.1, size=0.3
  ) +
  scale_y_continuous(labels = percent, limits = c(0, 0.1)) +
  scale_fill_manual(values = c("#1f78b4", "#a6cee3")) +
  labs(title = "Reduction in APE", y = "", x = "") +
    theme_bw() +
   theme(legend.position=c(0.9, 0.2), legend.title = element_blank(), plot.title = element_text(hjust = 0.5),) + 
  annotate("text",
           x = annotation_df$x,
           y = annotation_df$y,
           label = annotation_df$label,
           size = 3)
  # annotate("text",
  #          x = sample_annotation_df$x,
  #          y = sample_annotation_df$y,
  #          label = sample_annotation_df$label,
  #          size = 3)
```

```{r}
ggsave("./exp_result.pdf", unit = "in", width = 12 * 0.65, height = 6 * 0.65)
```

# Calculate the mean and CI of the reduction in APE
```{r}
rbind(plot_df %>%
  group_by(explanation, AI) %>%
  summarise(mean_payoff = mean(abs(human) - abs(hai)),
            sd_payoff = sd(abs(human) - abs(hai)),
            e = qt(0.975,df=n()-1)*sd_payoff/sqrt(n())) %>%
    mutate(low_CI95 = mean_payoff - e,
           high_CI95 = mean_payoff + e),
  plot_df %>%
  group_by(AI) %>%
  summarise(mean_payoff = mean(abs(human) - abs(hai)),
            sd_payoff = sd(abs(human) - abs(hai)),
            e = qt(0.975,df=n()-1)*sd_payoff/sqrt(n())) %>% 
    mutate(explanation = "Collapsing all explanations") %>%
    mutate(low_CI95 = mean_payoff - e,
           high_CI95 = mean_payoff + e)) %>% select(AI, explanation, mean_payoff, low_CI95, high_CI95, sd_payoff)
```

```{r}
plot_df %>% ungroup() %>% summarise(sd_payoff = sd(abs(human) - abs(hai)))
```


```{r}
plot_df %>% group_by(AI, explanation) %>% summarise(obs = n(), participant = n() / 12)
```

```{r}
pairs = list(list(c("pred1", "both"), c("pred1", "shap")),
             list(c("pred1", "both"), c("pred1", "none")),
             
             list(c("pred1"), c("pred2")),
             list(c("pred1", "both"), c("pred2", "both")))
plot_df = plot_df %>% mutate(reduced_ape = abs(human) - abs(hai))
pvalues = c()
for (p in pairs) {
  cond1 = p[[1]]
  cond2 = p[[2]]
  if (length(cond1) > 1) {
    data1 = (plot_df %>% filter((AI == cond1[[1]]) & (explanation == cond1[[2]])))$reduced_ape
    data2 = (plot_df %>% filter((AI == cond2[[1]]) & (explanation == cond2[[2]])))$reduced_ape
  } else {
    data1 = (plot_df %>% filter((AI == cond1[[1]])))$reduced_ape
    data2 = (plot_df %>% filter((AI == cond2[[1]])))$reduced_ape
  }
  pvalues = c(pvalues, t.test(data1, data2)$p.value)
}
pvalues = p.adjust(pvalues, method = "bonferroni")
print(pvalues)
```
